#!/usr/bin/env python3
"""Generate the AppleScripts and cheat sheet for the actions layer.

One script per action, written to a directory you point Alfred at. Alfred
binds each to its Meh chord (⌃⌥⇧ + the action's key); the keyboard's actions
layer sends that chord.

    ./actions-gen.py -o ~/bin/moom-keys -c ACTIONS.md

Scripts are plain AppleScript, so each can be run from Script Editor to see
what it does before any hotkey exists.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import actions as spec  # noqa: E402
import regions as region_spec  # noqa: E402


def applescript(action, titles):
    """The script for one action, as lines."""
    if action["kind"] == "app":
        return [
            f'-- Focus {action["name"]}',
            f'tell application id "{action["bundle"]}" to activate',
        ]

    lines = [f'-- {action["name"]}']
    for step in action["steps"]:
        kind = step[0]
        if kind == "layout":
            lines.append(f'tell application "Moom" to run "{step[1]}"')
        elif kind == "focus":
            lines.append(f'tell application id "{step[1]}" to activate')
        elif kind == "place":
            bundle, title = step[1], step[2]
            if title not in titles:
                raise SystemExit(
                    f'{action["name"]}: no region titled "{title}" in regions.py')
            lines += [
                f'tell application id "{bundle}" to activate',
                'delay 0.2',
                f'tell application "Moom" to run "{title}"',
            ]
        elif kind == "shortcut":
            lines.append(f'do shell script "shortcuts run " & quoted form of "{step[1]}"')
        elif kind == "url":
            lines.append(f'open location "{step[1]}"')
    return lines


def cheat_sheet(items, chord_glyphs):
    lines = [
        "# Actions",
        "",
        "Generated by `actions-gen.py` from `actions.py`. Hold **Tab** for the "
        f"actions layer, then the key. Each key sends {chord_glyphs} + itself, "
        "which Alfred turns into the script.",
        "",
        "| Key | Chord | Does |",
        "| --- | --- | --- |",
    ]
    for action in items:
        what = (f'Focus {action["name"]}' if action["kind"] == "app"
                else f'{action["name"]} — {len(action["steps"])} steps')
        lines.append(f'| `{action["key"]}` | {chord_glyphs}`{action["key"]}` | {what} |')
    lines += [
        "",
        "## Binding them in Alfred",
        "",
        "Each script needs one Alfred hotkey, once. In a workflow, add a "
        "**Hotkey** trigger, record the chord, and connect it to a "
        "**Run Script** action set to `/usr/bin/osascript` with the script's "
        "path. Alfred's Powerpack is required for workflows.",
        "",
        "## Modes",
        "",
    ]
    for action in items:
        if action["kind"] != "mode":
            continue
        lines += [f'### {action["name"]} (`{action["key"]}`)', ""]
        for step in action["steps"]:
            lines.append(f'* `{step[0]}` — {", ".join(str(part) for part in step[1:])}')
        lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("-o", "--output", required=True,
                        help="directory to write the AppleScripts into")
    parser.add_argument("-c", "--cheatsheet", help="also write a markdown cheat sheet")
    args = parser.parse_args()

    items = spec.actions()
    titles = {region["title"] for region in region_spec.regions()}

    out = Path(args.output).expanduser()
    out.mkdir(parents=True, exist_ok=True)
    for action in items:
        name = action["name"].lower().replace(" ", "-")
        path = out / f'{action["kind"]}-{name}.applescript'
        path.write_text("\n".join(applescript(action, titles)) + "\n")
        print(f'{action["key"]}  {action["name"]:<12} {path}')

    if args.cheatsheet:
        Path(args.cheatsheet).write_text(cheat_sheet(items, "⌃⌥⇧"))
        print(f"\nwrote {args.cheatsheet}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
