#!/usr/bin/env python3
"""Generate an Alfred workflow that binds every action's chord to its script.

An .alfredworkflow is a zip holding an info.plist, so the fourteen hotkeys
can be built rather than clicked in one at a time.

    ./alfred-gen.py -o ~/Desktop/moom-keys.alfredworkflow

Double-click the result to install it. Each action becomes a Hotkey trigger
wired to a Run Script action that calls `osascript` on the script in this
checkout — so the scripts stay the single copy, and editing config.yaml and
regenerating updates what the hotkeys do without touching Alfred again.

Rebuilding and reinstalling replaces the workflow in place, because the
bundle id stays the same.

This is the one piece that cannot be verified from outside Alfred. If it
refuses to import, ACTIONS.md lists every hotkey and command for binding by
hand, which is tedious but certain.
"""

from __future__ import annotations

import argparse
import plistlib
import sys
import uuid
import zipfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import config as config_module  # noqa: E402

BUNDLE_ID = "com.moom-keys.actions"

# NSEvent modifier flags, which is how Alfred records a hotkey's modifiers.
SHIFT, CONTROL, OPTION, COMMAND = 0x20000, 0x40000, 0x80000, 0x100000
CHORD_MODS = {"hyper": SHIFT | CONTROL | OPTION | COMMAND,
              "meh": SHIFT | CONTROL | OPTION}
GLYPHS = {"hyper": "⌃⌥⇧⌘", "meh": "⌃⌥⇧"}

# Alfred's Run Script languages. 0 is /bin/bash, which runs the script file
# rather than trying to interpret the path as source.
BASH = 0


def identifier(name):
    """A stable uid, so rebuilding does not scramble the canvas."""
    return str(uuid.uuid5(uuid.UUID("2d9f1f2c-6e5b-5a1d-9d3e-7c6b5a4f3e2d"),
                          name)).upper()


def hotkey_object(uid, keycode, mods, label):
    return {
        "config": {
            "action": 0, "argument": 3, "argumenttext": "",
            "focusedappvariable": False, "focusedappvariablename": "",
            "hotkey": keycode, "hotmod": mods, "hotstring": label,
            "leftcursor": False, "modsmode": 0, "relatedAppsMode": 0,
        },
        "type": "alfred.workflow.trigger.hotkey",
        "uid": uid,
        "version": 2,
    }


def script_object(uid, command):
    return {
        "config": {
            "concurrently": False, "escaping": 102, "script": command,
            "scriptargtype": 0, "scriptfile": "", "type": BASH,
        },
        "type": "alfred.workflow.action.script",
        "uid": uid,
        "version": 2,
    }


def workflow(cfg, scripts, chord):
    objects, connections, uidata = [], {}, {}
    mods = CHORD_MODS[chord]

    for index, action in enumerate(cfg.actions):
        name = action["name"].lower().replace(" ", "-")
        path = scripts / f'{action["kind"]}-{name}.applescript'
        trigger = identifier(f"hotkey:{action['name']}")
        runner = identifier(f"script:{action['name']}")

        keycode = config_module.KEYS[action["key"]][0]
        objects.append(hotkey_object(trigger, keycode, mods, action["key"]))
        objects.append(script_object(runner, f'osascript "{path}"'))
        connections[trigger] = [{"destinationuid": runner, "modifiers": 0,
                                 "modifiersubtext": "", "vitoclose": False}]
        uidata[trigger] = {"xpos": 40, "ypos": 40 + index * 110}
        uidata[runner] = {"xpos": 320, "ypos": 40 + index * 110}

    listing = "\n".join(
        f'{GLYPHS[chord]}{action["key"]}  —  {action["name"]}'
        for action in cfg.actions)
    return {
        "bundleid": BUNDLE_ID,
        "category": "Tools",
        "connections": connections,
        "createdby": "moom-keys",
        "description": "Window regions and app actions, generated from config.yaml",
        "disabled": False,
        "name": "moom-keys actions",
        "objects": objects,
        "readme": ("Generated by alfred-gen.py. Each hotkey runs an AppleScript "
                   "in the moom-keys checkout, so editing config.yaml and "
                   "regenerating changes what these do — no need to touch this "
                   "workflow again unless keys change.\n\n" + listing),
        "uidata": uidata,
        "variablesdontexport": [],
        "version": "1.0",
        "webaddress": "",
    }


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("-o", "--output", required=True,
                        help="the .alfredworkflow file to write")
    parser.add_argument("--scripts",
                        default=str(Path(__file__).resolve().parent / "scripts"),
                        help="directory the hotkeys should run scripts from")
    args = parser.parse_args()

    cfg = config_module.load()
    print(f"read {config_module.CONFIG.name} with {cfg.parser}\n")

    scripts = Path(args.scripts).expanduser().resolve()
    missing = [action["name"] for action in cfg.actions
               if not (scripts / f'{action["kind"]}-'
                       f'{action["name"].lower().replace(" ", "-")}.applescript').exists()]
    if missing:
        raise SystemExit(f"no script for {', '.join(missing)} — run actions-gen.py first")

    chord = cfg.layer("actions_layer").get("chord", "meh")
    output = Path(args.output).expanduser()
    with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("info.plist",
                         plistlib.dumps(workflow(cfg, scripts, chord)))

    for action in cfg.actions:
        print(f'{GLYPHS[chord]}{action["key"]:<3} {action["name"]}')
    print(f"\nwrote {output}")
    print("Double-click it to install. Alfred will ask to approve the hotkeys.")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except BrokenPipeError:
        sys.exit(0)
