#!/usr/bin/env python3
"""Generate an Alfred workflow that binds every action's chord to its script.

Each action becomes a Hotkey trigger wired to a Run Script action calling
`osascript` on the script in this checkout, so the scripts stay the single
copy: editing config.yaml and regenerating changes what the hotkeys do
without touching Alfred again.

    ./alfred-gen.py --install

**Install, do not import.** Alfred strips the hotkeys out of an imported
.alfredworkflow — confirmed by exporting one back and finding every hotkey it
was given reading `hotkey: 0, hotmod: 0`, while the ones assigned by hand read
exactly what this generates. Writing the workflow into Alfred's own workflows
folder skips that sanitising and the hotkeys arrive live.

    ./alfred-gen.py -o ~/Desktop/moom-keys.alfredworkflow

still writes the importable file, for moving it to another machine — where
its hotkeys will need recording by hand, for the same reason.
"""

from __future__ import annotations

import argparse
import plistlib
import sys
import uuid
import zipfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import config as config_module  # noqa: E402

BUNDLE_ID = "com.moom-keys.actions"
# The folder Alfred keeps installed workflows in, and where its preferences
# say to look if they have been moved to Dropbox or iCloud.
WORKFLOW_FOLDER = "user.workflow.moom-keys"
ALFRED_PREFS = Path("~/Library/Preferences/"
                    "com.runningwithcrayons.Alfred-Preferences.plist").expanduser()
DEFAULT_SYNC = Path("~/Library/Application Support/Alfred").expanduser()

# NSEvent modifier flags, which is how Alfred records a hotkey's modifiers.
SHIFT, CONTROL, OPTION, COMMAND = 0x20000, 0x40000, 0x80000, 0x100000
CHORD_MODS = {"hyper": SHIFT | CONTROL | OPTION | COMMAND,
              "meh": SHIFT | CONTROL | OPTION}
GLYPHS = {"hyper": "⌃⌥⇧⌘", "meh": "⌃⌥⇧"}

# Alfred's Run Script languages. 0 is /bin/bash, which runs the script file
# rather than trying to interpret the path as source.
BASH = 0


def identifier(name):
    """A stable uid, so rebuilding does not scramble the canvas."""
    return str(uuid.uuid5(uuid.UUID("2d9f1f2c-6e5b-5a1d-9d3e-7c6b5a4f3e2d"),
                          name)).upper()


def hotkey_object(uid, keycode, mods, label):
    # Exactly the shape Alfred writes for a hotkey assigned by hand, including
    # the absence of "argumenttext", which it drops once a key is recorded.
    return {
        "config": {
            "action": 0, "argument": 3,
            "focusedappvariable": False, "focusedappvariablename": "",
            "hotkey": keycode, "hotmod": mods, "hotstring": label,
            "leftcursor": False, "modsmode": 0, "relatedAppsMode": 0,
        },
        "type": "alfred.workflow.trigger.hotkey",
        "uid": uid,
        "version": 2,
    }


def script_object(uid, command):
    return {
        "config": {
            "concurrently": False, "escaping": 102, "script": command,
            "scriptargtype": 0, "scriptfile": "", "type": BASH,
        },
        "type": "alfred.workflow.action.script",
        "uid": uid,
        "version": 2,
    }


def workflow(cfg, scripts, chord):
    objects, connections, uidata = [], {}, {}
    mods = CHORD_MODS[chord]

    for index, action in enumerate(cfg.actions):
        name = action["name"].lower().replace(" ", "-")
        path = scripts / f'{action["kind"]}-{name}.applescript'
        trigger = identifier(f"hotkey:{action['name']}")
        runner = identifier(f"script:{action['name']}")

        keycode = config_module.KEYS[action["key"]][0]
        objects.append(hotkey_object(trigger, keycode, mods, action["key"]))
        objects.append(script_object(runner, f'osascript "{path}"'))
        connections[trigger] = [{"destinationuid": runner, "modifiers": 0,
                                 "modifiersubtext": "", "vitoclose": False}]
        # Notes label each object on Alfred's canvas, so if a hotkey has to
        # be recorded by hand it is obvious which one it is.
        uidata[trigger] = {"xpos": 40, "ypos": 40 + index * 110,
                           "note": f'{GLYPHS[chord]}{action["key"]}  {action["name"]}'}
        uidata[runner] = {"xpos": 320, "ypos": 40 + index * 110,
                          "note": action["name"]}

    listing = "\n".join(
        f'{GLYPHS[chord]}{action["key"]}  —  {action["name"]}'
        for action in cfg.actions)
    return {
        "bundleid": BUNDLE_ID,
        "category": "Tools",
        "connections": connections,
        "createdby": "moom-keys",
        "description": "Window regions and app actions, generated from config.yaml",
        "disabled": False,
        "name": "moom-keys actions",
        "objects": objects,
        "readme": ("Generated by alfred-gen.py. Each hotkey runs an AppleScript "
                   "in the moom-keys checkout, so editing config.yaml and "
                   "regenerating changes what these do — no need to touch this "
                   "workflow again unless keys change.\n\n" + listing),
        "uidata": uidata,
        "variablesdontexport": [],
        "version": "1.0",
        "webaddress": "",
    }


def alfred_workflows():
    """Where Alfred keeps installed workflows, following its sync folder."""
    folder = DEFAULT_SYNC
    if ALFRED_PREFS.exists():
        with open(ALFRED_PREFS, "rb") as handle:
            synced = plistlib.load(handle).get("syncfolder")
        if synced:
            folder = Path(synced).expanduser()
    return folder / "Alfred.alfredpreferences" / "workflows"


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("-o", "--output",
                        help="write an importable .alfredworkflow here instead "
                             "of installing (its hotkeys will not survive import)")
    parser.add_argument("--install", action="store_true",
                        help="write the workflow into Alfred's workflows folder, "
                             "where the hotkeys arrive live")
    parser.add_argument("--to", help="install into this folder instead of the "
                                     "one Alfred's preferences point at")
    parser.add_argument("--scripts",
                        default=str(Path(__file__).resolve().parent / "scripts"),
                        help="directory the hotkeys should run scripts from")
    args = parser.parse_args()

    cfg = config_module.load()
    print(f"read {config_module.CONFIG.name} with {cfg.parser}\n")

    scripts = Path(args.scripts).expanduser().resolve()
    missing = [action["name"] for action in cfg.actions
               if not (scripts / f'{action["kind"]}-'
                       f'{action["name"].lower().replace(" ", "-")}.applescript').exists()]
    if missing:
        raise SystemExit(f"no script for {', '.join(missing)} — run actions-gen.py first")

    if not args.install and not args.output:
        raise SystemExit("nothing to do: pass --install, or -o to write a file")

    chord = cfg.layer("actions_layer").get("chord", "meh")
    built = workflow(cfg, scripts, chord)
    for action in cfg.actions:
        print(f'{GLYPHS[chord]}{action["key"]:<3} {action["name"]}')

    if args.output:
        output = Path(args.output).expanduser()
        with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as archive:
            archive.writestr("info.plist", plistlib.dumps(built))
        print(f"\nwrote {output}")
        print("Importing this strips the hotkeys — Alfred does that to every "
              "imported workflow. Use --install on the machine that runs it.")

    if args.install:
        folder = Path(args.to).expanduser() if args.to else alfred_workflows()
        if not folder.is_dir():
            raise SystemExit(
                f"{folder} does not exist — is Alfred installed? Its workflows "
                "folder moves with the sync folder, so pass --to if yours is "
                "somewhere else.")
        target = folder / WORKFLOW_FOLDER
        target.mkdir(exist_ok=True)
        with open(target / "info.plist", "wb") as handle:
            plistlib.dump(built, handle)
        print(f"\ninstalled into {target}")
        print("Restart Alfred to pick it up: its workflow list is read at launch.")
        print("Delete any copy you imported earlier first — same bundle id, "
              "so two copies would fight over the same chords.")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except BrokenPipeError:
        sys.exit(0)
